### PR TITLE
For Win2019 server, add permissions to admin group instead of user

### LINKED ISSUE #47: [Bug]: After installation in 2019 server, I get access denied error with another admin user
### Checklist

- [X] I have give this issue a title starting with the text `[Bug]:` to signify it is a bug.
- [X] I have performed the steps in the [Troubleshooting](https://github.com/asheroto/winget-install#troubleshooting) section and confirm that the issue only occurs with this script.
- [X] I have restarted my computer to confirm this is not a transitory problem.

- [X] I have verified that I am using the latest version of winget-install.

- [X] I have verified that this issue is NOT security related (please create [security advisory](https://github.com/asheroto/winget-install/security/advisories) if so).

### What You Are Seeing?

I am in a setup with multiple administrators on a Windows 2019 server. Winget works great with the install script as long as I use it with the same user I have installed it with.

When I run winget with another user, which has of course also admin permission, I get an access denied error.

### System Details

Windows Server 2019

### Additional Context

I think the reason is this code, where on Windows 2019 server "only" the current user gets full control rights.

```
            $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule($env:USERNAME, "FullControl", "ContainerInherit,ObjectInherit", "None", "Allow")
```

There might abe a reason for this which I am unaware. I am currently testing giving rights to the Administrators group and would submit a PR if it works.

### PR DESCRIPTION
**Pull request by andygruber**
Fixes #47

### CODE REVIEW

**Comment by asheroto** [comment]
Great catch!

I'll merge the PR. Thanks so much!

**Comment by asheroto** [comment]
Just running some tests on this first.

**Comment by asheroto** [comment]
Merged.

Are you able to run this script? I keep seeing errors when running even the previous winget script on several virtual machines. I made some changed to fix it but haven't pushed it out yet.

https://raw.githubusercontent.com/asheroto/winget-install/refs/heads/master/winget-install.ps1

**Comment by asheroto** [comment]
Do you mind testing this one as well for me? winget-cli now supports a Repair-WingetPackageManager function which handles the install and dependencies, so I'm considering switching over to that method.

https://raw.githubusercontent.com/asheroto/winget-install/refs/heads/AddEnvironmentPathTest/winget-install.ps1

**Comment by asheroto** [comment]
Looks like it works. I pushed out version `5.0.0`.

**Comment by andygruber** [comment]
> Looks like it works. I pushed out version `5.0.0`.

sry I was not able to assist in testing, ty for your work!

**Comment by asheroto** [comment]
No worries at all! I appreciate your time! 😊

**Pull request merged**
