### PR TITLE
Alternate method

### PR DESCRIPTION
**Pull request by asheroto**

### CODE REVIEW

**Comment by asheroto** [comment]
@MisterZeus @ChrisTitusTech

What do you guys think about this alternate method? It uses the store.rg-adguard.net method of getting a direct download link... which makes me feel a little weird, so I made a separate branch to get your input. It is a legit site and many scripts use this method. I think Chris even [mentions it on his blog](https://christitus.com/installing-appx-without-msstore/).

https://github.com/asheroto/winget-install/blob/Alternate-Method/winget-install.ps1

**Comment by asheroto** [comment]
Implemented twice:
https://github.com/asheroto/winget-install/blob/77ac4aeb6b554e13af54d563f8169a82aa55960e/winget-install.ps1#L353-L359
https://github.com/asheroto/winget-install/blob/77ac4aeb6b554e13af54d563f8169a82aa55960e/winget-install.ps1#L428-L434

**Comment by MisterZeus** [comment]
@asheroto works for me!

**Comment by asheroto** [comment]
Thanks, will merge.

**Pull request closed without merging**
